version: "3.3"

services:
  telegram_media_downloader:
    image: ghcr.io/majingyifighting/telegram_media_downloader:latest
    build: .
    ports:
      # Here is what you need to edit
      - "5000:5000"
    #environment:
    #  - http_proxy=http://192.168.101.30:10811
    #  - https_proxy=http://192.168.101.30:10811
    volumes:
      # Here is what you need to edit
      - "./downloads/:/app/downloads/"

      # Rclone
      - "$HOME/.config/rclone/:$HOME/.config/rclone/"

      # The following is what you don't need to edit
      - "./config.yaml:/app/config.yaml"
      - "./data.yaml:/app/data.yaml"
      - "./log/:/app/log/"
      - "./sessions/:/app/sessions"
      - "./temp/:/app/temp"
    # unless-stopped: restart the container unless it is explicitly stopped
    # This enables the container to restart when the download speed is too low
    # 除非手动停止，否则总是重启容器。这样在下载速度检测功能触发时能够自动重启容器
    restart: unless-stopped
# volumes:
#   sessions:
#   temp:
